FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y wget libnss3 nss-plugin-pem ca-certificates python3 libcurl4-openssl-dev build-essential

ENV NODE_VERSION=16.13.0
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"

WORKDIR /testing
COPY ./ /testing
COPY /libcurl-impersonate /usr/local/lib/
RUN ln -s /usr/local/lib/libcurl-impersonate-ff.so.4.8.0 /usr/local/lib/libcurl.so

RUN npm install node-libcurl --build-from-source --curl_libraries='-Wl,-rpath /usr/local/lib -lcurl'

ENV LD_PRELOAD=/usr/local/lib/libcurl.so
ENV CURL_IMPERSONATE=ff109

CMD ["node", "index.js"]